repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.108.0
    hooks:
      - id: terraform_fmt
        name: Terraform fmt
        description: Rewrites all Terraform configuration files to a canonical format
        entry: terraform_fmt
        language: script
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$

      - id: terraform_validate
        name: Terraform validate
        description: Validates all Terraform configuration files
        entry: terraform_validate
        language: script
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$
        require_serial: true

      - id: terraform_docs
        name: Terraform docs
        description: Inserts input and output documentation into README.md
        entry: terraform_docs
        language: script
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$

      - id: terraform_tflint
        name: Terraform tflint
        description: Lints Terraform files with tflint
        entry: terraform_tflint
        language: script
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/.*$
